"""create decisions and escalations tables

Revision ID: 210654d8fc7c
Revises: cfd18cebc7e1
Create Date: 2026-06-25 15:47:21.053508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '210654d8fc7c'
down_revision: Union[str, Sequence[str], None] = 'cfd18cebc7e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('approve', 'remove', 'warn', 'restrict', 'escalate', 'request_info', name='action'), nullable=False),
    sa.Column('rationale', sa.String(), nullable=False),
    sa.Column('policy_reference', sa.String(), nullable=True),
    sa.Column('confidence', sa.Enum('low', 'medium', 'high', name='confidencelevel'), nullable=False),
    sa.Column('time_on_case_secs', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('escalations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('initiated_by', sa.Uuid(), nullable=False),
    sa.Column('escalation_type', sa.Enum('senior_review', 'policy_review', 'legal', 'quality_check', name='escalationtype'), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('to_queue_id', sa.Uuid(), nullable=True),
    sa.Column('to_reviewer_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('to_queue_id IS NOT NULL OR to_reviewer_id IS NOT NULL', name='ck_escalation_target'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_queue_id'], ['queues.id'], ),
    sa.ForeignKeyConstraint(['to_reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('escalations')
    op.drop_table('decisions')
    sa.Enum('approve', 'remove', 'warn', 'restrict', 'escalate', 'request_info', name='action').drop(op.get_bind())
    sa.Enum('low', 'medium', 'high', name='confidencelevel').drop(op.get_bind())
    sa.Enum('senior_review', 'policy_review', 'legal', 'quality_check', name='escalationtype').drop(op.get_bind())
    # ### end Alembic commands ###
