"""create cases table

Revision ID: cfd18cebc7e1
Revises: c572e3d53fd4
Create Date: 2026-06-25 15:01:08.546787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cfd18cebc7e1'
down_revision: Union[str, Sequence[str], None] = 'c572e3d53fd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('content_type', sa.Enum('text', 'image', 'video', 'audio', 'account', name='contenttype'), nullable=False),
    sa.Column('content_ref', sa.String(), nullable=False),
    sa.Column('content_snapshot', sa.String(), nullable=True),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='severity'), nullable=False),
    sa.Column('status', sa.Enum('unassigned', 'assigned', 'in_review', 'escalated', 'resolved', name='casestatus'), nullable=False),
    sa.Column('queue_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('sla_deadline', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('case_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cases')
    sa.Enum('text', 'image', 'video', 'audio', 'account', name='contenttype').drop(op.get_bind())
    sa.Enum('low', 'medium', 'high', 'critical', name='severity').drop(op.get_bind())
    sa.Enum('unassigned', 'assigned', 'in_review', 'escalated', 'resolved', name='casestatus').drop(op.get_bind())
    # ### end Alembic commands ###
